name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to G H Pages
      env:
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
      run: |
        git config --global user.email "guntupallikoteswararao2016@gmail.com"
        git config --global user.name "guntupallikoteswararao2016"
        git remote set-url origin https://guntupallikoteswararao2016:a4bcff702f0fa4c6500a04484b4033e30ac5b99a@github.com/guntupallikoteswararao2016/ui-core-invoice.git
        npm run deploy
