name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to G H Pages
      run: |
        git config --global user.email "guntupallikoteswararao2016@gmail.com"
        git config --global user.name "guntupallikoteswararao2016"
        git remote set-url origin https://guntupallikoteswararao2016:b971e22b645366a1f2ea7310e0073403414b6820@github.com/guntupallikoteswararao2016/ui-core-invoice.git"
        npm run deploy
